version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Building self-contained Fat JAR from our custom repository..."
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/chess-1.0-SNAPSHOT.jar
  discard-paths: yes
